spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/opcua_db
    username: postgres
    password: postgres
    hikari:
      schema: opcua_schema
      connection-init-sql: create schema if not exists opcua_schema
      connection-timeout: 10000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: scada-service

opcua:
  tags:
    - "Simulation Examples.Functions.Random1"
    - "Simulation Examples.Functions.Random2"
    - "Simulation Examples.Functions.Random3"
    - "Simulation Examples.Functions.Random4"
    - "Simulation Examples.Functions.Random5"
    - "Simulation Examples.Functions.Random6"
    - "Simulation Examples.Functions.Random7"
    - "Simulation Examples.Functions.Random8"

app:
  opc-server-address: "opc.tcp://127.0.0.1:49320"