spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/opcua_db
    username: postgres
    password: postgres
    hikari:
      schema: opcua_schema
      connection-init-sql: create schema if not exists opcua_schema
      connection-timeout: 10000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: scada-service

app:
  opc-server-address: "opc.tcp://127.0.0.1:49320"